### ISSUE TITLE
Implement NFC transfer

### ISSUE THREAD

**Issue by a1gemmel** [AwesomePossum446/Cordial#10]

**Comment by a1gemmel** [comment]
ヽ༼ຈل͜ຈ༽ﾉ Got a second phone ヽ༼ຈل͜ຈ༽ﾉ

**Comment by a1gemmel** [comment]
I'm admitting defeat on this one. The [nfc-react-native](https://github.com/Lube/nfc-react-native) package just doesn't seem to work well, and there's no other package that supports writing NFC tags. I'll push a branch with the setup I was using in case anyone else wants to have a crack at it.

Three big problems I encountered:
- this package makes the app crash *all the time*. Apparently it's related to unresolved fetch style requests, there's no way within the package to cancel or end read/write requests so they seem to hang around until they make the app crash.
- the DeviceEventEmitter API doesn't seem to be working as the example app suggests. I could not get any of the custom native events to fire, which stopped me from even being able to see if tag reading worked. I was able to write tags and verify them with a third-party NFC-reader app.
- the package only supports the Mifare Classic spec, which is a paltry 750 bytes of transfer. (A workaround for that would be to use NFC to negotiate a bluetooth connection, then use that. But that's a lot of work.)


@arafeek @radusepe @shivangipatwardhan2018 
anyone else brave enough to take a shot, or do we want to scrap the feature?

**Comment by arafeek** [comment]
Seems like a great thing we can mention as a challenge during the final presentation. We have email and QR working well so those should be good sharing wise. I'm hoping to have firebase working for image syncing tomorrow so once we can just focus on making sure sharing via the methods we have works well.

**Comment by a1gemmel** [comment]
Closing as won't do  ヽ༼ຈل͜ຈ༽ﾉ
