### ISSUE TITLE
As a user, I want to be able to set up an account and create a basic card.

### ISSUE THREAD

**Issue by shivangipatwardhan2018** [AwesomePossum446/Cordial#17]

**Comment by shivangipatwardhan2018** [comment]
Data validation (handle malicious input)

**Comment by a1gemmel** [comment]
@arafeek how much do you think this will overlap with the individual contact view in #29?

**Comment by arafeek** [comment]
Gonna be working on this today. The end stage of this (once the card has been successfully created) will result in the user being taken to the view in #29 so probably pretty heavily. I'd imagine we could create one set of components for rendering full cards (with optional params that make them editable, etc.)
