### ISSUE TITLE
Application routing

### ISSUE THREAD

**Issue by a1gemmel** [AwesomePossum446/Cordial#22]
Need to flesh out react-router-native routing for all of the application views and stub out each view.

**Comment by arafeek** [comment]
Are you working on this? I have it like 95% done, just need to do cleanup and should get PR up by EOD

**Comment by a1gemmel** [comment]
I started fleshing things out, but if you have something working then go for it. In future you should create an issue so we know it's being worked on

**Comment by a1gemmel** [comment]
I feel like this is done
