### ISSUE TITLE
Settings View

### ISSUE THREAD

**Issue by a1gemmel** [AwesomePossum446/Cordial#34]
As a user, I would like a settings view where I can toggle my preferences for the app's behavior. 

As a developer, I want to know what settings data will look like in order to design the view and related redux things: If it's all going to be boolean switches then that makes life really easy.

@radusepe do you have additional thoughts on this in regards to changes from the low-res mockup?

**Comment by radusepe** [comment]
The only settings I can think of, that we've already talked about, are toggleable options:
- auto import cordial contacts to device default contacts app
- compact profile view

Additionally we can add an option to make the Sharing View be the screen that opens on default.
