### ISSUE TITLE
Decide on full tech stack

### ISSUE THREAD

**Issue by arafeek** [AwesomePossum446/Cordial#4]
Besides settling on using React Native to build our app, are we all comfortable with using the following stuff?

Redux (state management)
JavaScript / ES6 / ES2016
ImmutableJS (alongside redux, to prevent state mutations)
react-router (app navigation)

figured we might as well have a thread to discuss benefits / ideas / concerns

**Comment by arafeek** [comment]
@radusepe @a1gemmel @shivangipatwardhan2018

**Comment by a1gemmel** [comment]
I have used and like all of that except for ImmutableJS, which I'm open to trying. As devil's advocate I would say that it's probably overkill if we all understand non-mutative object manipulation in Javascript.

We'll also need to pick NFC/Bluetooth libraries as well, [this](https://github.com/Polidea/react-native-ble-plx) seems to be the canonical Bluetooth library but I've never used it so ¯\\_(ツ)_/¯

If we want to standardize a utility library, I'm partial to Lodash 4.

As per my comment in #5, if we're going with a backend API, I would suggest:
web.py + mongoDB 
NodeJs + Express + mongoDB is cool too, my hosting package doesn't support it but I'm sure someone else's does or we can get AWS credits or something.
