### ISSUE TITLE
Application Crashes when clicking on QR icon

### ISSUE THREAD

**Issue by radusepe** [AwesomePossum446/Cordial#47]
I am experiencing the following behavior on both iOS and android simulators, as well as my iPhone. Clicking on the QR icon in this screenshot causes the application to crash
![image](https://cloud.githubusercontent.com/assets/9058910/23344761/d59e71a4-fc4f-11e6-9784-f9f0ad7c4183.png)

**Comment by radusepe** [comment]
Additional screenshots
![image](https://cloud.githubusercontent.com/assets/9058910/23344768/204a2a72-fc50-11e6-8045-bdb8de9166f3.png)

![image](https://cloud.githubusercontent.com/assets/9058910/23344769/23b1523a-fc50-11e6-9a44-6459f4177a5e.png)

**Comment by shivangipatwardhan2018** [comment]
Okay, it was working for my android phone + emulator will double check.
