### ISSUE TITLE
Come up with functionality ideas.

### ISSUE THREAD

**Issue by arafeek** [AwesomePossum446/Cordial#5]
We all have a cursory idea of what our app should do, but we can individually come up with some things we'd like to have in there. We can use the beginning of the next class to go through all our ideas and decide what we'll actually implement.

**Comment by a1gemmel** [comment]
I would like to see data synchronization and updates. You would be able to update your contact profile and publish that change to a central source, and would also have the ability to pull updates to your contacts.

Of course this would require a database & API, but it would be a relatively simple CRUD backend.
