### ISSUE TITLE
UI/UX for custom field creation

### ISSUE THREAD

**Issue by a1gemmel** [AwesomePossum446/Cordial#73]
What does this work flow look like?
Mockups or a decision tree would be nice.

**Comment by radusepe** [comment]
The very first option in the 'Choose a field type' screen should be 'Create Custom Field'. Clicking on this opens up a prompt (default device style) where the user just inputs the name for that custom field (ie. Phone Number). This field then shows up on the card the same way any other field would show up when clicked on, Github for example.

![image](https://cloud.githubusercontent.com/assets/9058910/24076713/291ca1e8-0c0e-11e7-8705-1565f6d15dbb.png)

![image](https://cloud.githubusercontent.com/assets/9058910/24076714/2da0dcac-0c0e-11e7-8cb9-98813793b494.png)

Thoughts? This feels like the cleanest way to me.
